### ISSUE TITLE
Corrigir as infos dos grupos KDE Brasil e do canal Qt Mobile

### ISSUE THREAD

**Issue by filipesaraiva** [listatelegram/listatelegram.github.io#143]
Pelo que vejo aqui no repositório houveram muitas contribuições mas elas ainda não foram incorporadas ao site em si, o que significa que as informações lá estão desatualizadas.

Estou dando esse toque nos mantenedores para que eles atualizem o site. :)

**Comment by somatorio** [comment]
pode me dar um exemplo? todos os que eu verifiquei aqui, estão na lista
essa lista é atualizada automaticamente pelo github mesmo, então pode ser algum erro no arquivo de markdown

**Comment by filipesaraiva** [comment]
Ah rapaz, desculpe então. Realmente, o meu é que está com problema. No caso é esse do grupo [KDE Brasil](https://github.com/listatelegram/listatelegram.github.io/blob/master/_posts/kdebrasil.markdown) e o do [Qt Mobile](https://github.com/listatelegram/listatelegram.github.io/blob/master/_posts/qtmobile.markdown).

**Comment by somatorio** [comment]
o que eu notei é que eles estão sem categoria, vou editar na mão grande aqui mesmo e veremos :p

**Comment by somatorio** [comment]
achei, o problema era o nome dos arquivos, não estava começando com a data (o formato é `yyyy-mm-dd-nome.markdown`)
