### ISSUE TITLE
categories?

### ISSUE THREAD

**Issue by jprando** [listatelegram/listatelegram.github.io#213]
ao criar um registro na lista, tem a opcao categories, poderia explicar melhor aqui ou no README como é ou deveria ser usado esse campo?

é algo interno? é algo da tecnologia que voce esta usando para compilacao da pagina?
é para registrar categorias mesmo? não é exibido na lista então pra que serve?

essa sao as minhas duvidas

ate+

**Comment by christyanbrayan** [comment]
Chegou a entender?

**Comment by jprando** [comment]
> 
> 
> Chegou a entender?

nao, sem feedback por enquanto!

**Comment by christyanbrayan** [comment]
puts, acho que abandonaram. tem vários issues e prs abertos

**Comment by somatorio** [comment]
Anos depois vem aqui a resposta: o plano era ter uma sessão de categorias pra organizar os canais na lista, mas a vida e os compromissos atrapalharam isso :(

Edit: se alguém quiser arrumar isso eu agradeço :P
