### ISSUE TITLE
Ordenação dos Grupos

### ISSUE THREAD

**Issue by jtemporal** [listatelegram/listatelegram.github.io#69]
Gente tudo bom?!

poderíamos ver um jeito de ordenar os grupos em ordem alfabetica ne?! o que acham?

=)

**Comment by somatorio** [comment]
é uma ótima idéia :)
(infelizmente) o [jekyll](http://jekyllrb.com/) não tem um suporte nativo pra isso :/  
o que significa que teríamos de fazer "na mão" o ordenamento, eu até pesquisei sobre como fazer isso mas confesso que fiquei bem perdido, hehe

mas se alguém quiser fazer PR com a solução... :D

edit: outra solução seria migrar do [jekyll](http://jekyllrb.com/) pro [hugo](https://gohugo.io/) - https://gohugo.io/tutorials/github-pages-blog/

**Comment by rpaggi** [comment]
Estou pesquisando alguma forma de fazer isso ai, se eu conseguir envio um PR.

**Comment by srgfrancisco** [comment]
Também acho que a organização poderia ser feita entre temas ao qual os grupos estão relacionados.
Exemplo: Infra, QA, Dev, Security, etc.

Não sei qual granularidade seria a ideal, mas subtemas também podem ser úteis.
Ex: Infra ─> Redes, Cloud Computing, DevOps, etc.

**Comment by somatorio** [comment]
@sergiofsfilho isso parece ser mais fácil... já tem "category" entre os dados a serem inseridos... então acho que dá pra separar por categorias bem fácil... vou tentar ver isso o mais breve possível (claro que PRs sempre são bem-vindas)

**Comment by somatorio** [comment]
ordenação por ordem alfabética feita por @talesteixeira
