### ISSUE TITLE
Links quebrados ou expirados

### ISSUE THREAD

**Issue by albertopida** [listatelegram/listatelegram.github.io#7]
elastic-users-br
https://telegram.me/joinchat/AejjFQCHmDHk7796cRQXYA

vagrant-users-br
(https://telegram.me/joinchat/AejjFQZcA-IOjJmRXzmcIA)

**Comment by somatorio** [comment]
basta enviar a correção amigo :)

**Comment by albertopida** [comment]
A correção é tirar os links?

**Comment by somatorio** [comment]
não, caso saibas o link correto enviar a correção dele

**Comment by albertopida** [comment]
Esse é o problema, não sei o link correto.. ;]

**Comment by somatorio** [comment]
nesse caso temos duas opções, remover os links (o que eu faria se ainda fosse no meu blog) ou editar o post informando que o link está inválido e pedindo pra corrigirem... :)

ps: do devops e do shell eu já consegui os links, vou atualizar agora

**Comment by albertopida** [comment]
Vou finalizar a issue e mandar um PR com os links que estão off.

**Comment by albertopida** [comment]
Vou finalizar a issue e mandar um PR com os links que estão off.
